swagger: '2.0'
info:
  version: '1.0.0'
  title: Malina licensing service
  description: Malina licensing service
  termsOfService: All rigths reserved. Syntactik 2017.
  contact:
    name: Maxim Trushin
    email: Maxim.Trushin@syntactik.com  
    url: http://syntactik.com
host: malinalicensing.azurewebsites.net
basePath: /api/subscription
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /leadIsConfirmed:
    get:
      description: Checks if Lead Info has confirmed email
      operationId: leadIsConfirmed
      parameters:
        - name: email
          in: query
          description: leads email
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            type: integer
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /signupLead:
    get:
      description: Adds Lead to DB and campaign
      operationId: signupLead
      parameters:
        - name: email
          in: query
          description: lead's email
          required: true
          type: string
        - name: name
          in: query
          description: lead's name
          required: true
          type: string          
        - name: position
          in: query
          description: lead's position
          required: false
          type: string                
        - name: company
          in: query
          description: lead's company
          required: false
          type: string                          
        - name: machineId
          in: query
          description: machine Id
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            type: string
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
  /requestLicense:
    get:
      description: Checks if Lead Info has confirmed email
      operationId: requestLicense
      parameters:
        - name: email
          in: query
          description: leads email
          required: true
          type: string
        - name: machineId
          in: query
          description: machine Id
          required: true
          type: string
        - name: machineName
          in: query
          description: network name
          required: true
          type: string          
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/licenseInfo'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
  licenseInfo:
    type: object
    properties:
      uid:
        type: string
      type:
        type: string
      license:
        type: string
      expiresAt:
        type: string
        format: date
      confirmed:
        type: boolean
      errorMessage:
        type: string
      valid:
        type: boolean



    