
// This file has been generated by the GUI designer. Do not modify.
namespace Syntactik.MonoDevelop.License
{
	public partial class ConfirmationStatusDialog
	{
		private global::Gtk.HBox hbox2;

		private global::Gtk.Image loaderImage;

		private global::Gtk.VSeparator vseparator1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label labelLineTop;

		private global::Gtk.Label labelEmail;

		private global::Gtk.Label labelLineBottom;

		private global::Gtk.Button buttonCancel;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Syntactik.MonoDevelop.License.ConfirmationStatusDialog
			this.Name = "Syntactik.MonoDevelop.License.ConfirmationStatusDialog";
			this.Title = global::Mono.Unix.Catalog.GetString("Confirmation email");
			this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-dialog-authentication", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.BorderWidth = ((uint)(5));
			this.Resizable = false;
			this.DestroyWithParent = true;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Internal child Syntactik.MonoDevelop.License.ConfirmationStatusDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.loaderImage = new global::Gtk.Image();
			this.loaderImage.Name = "loaderImage";
			this.hbox2.Add(this.loaderImage);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.loaderImage]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vseparator1 = new global::Gtk.VSeparator();
			this.vseparator1.Name = "vseparator1";
			this.hbox2.Add(this.vseparator1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vseparator1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelLineTop = new global::Gtk.Label();
			this.labelLineTop.TooltipMarkup = "Confirmation email has been sent to.\nWaiting for confirmation.";
			this.labelLineTop.Name = "labelLineTop";
			this.labelLineTop.Xalign = 0F;
			this.labelLineTop.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Confirmation email has been sent to:</b>");
			this.labelLineTop.UseMarkup = true;
			this.vbox2.Add(this.labelLineTop);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelLineTop]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelEmail = new global::Gtk.Label();
			this.labelEmail.Name = "labelEmail";
			this.labelEmail.LabelProp = global::Mono.Unix.Catalog.GetString("test@mail.com");
			this.vbox2.Add(this.labelEmail);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelEmail]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelLineBottom = new global::Gtk.Label();
			this.labelLineBottom.Name = "labelLineBottom";
			this.labelLineBottom.Xalign = 0F;
			this.labelLineBottom.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Waiting for confirmation.</b>");
			this.labelLineBottom.UseMarkup = true;
			this.vbox2.Add(this.labelLineBottom);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelLineBottom]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.hbox2.Add(this.vbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox2]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			w1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1[this.hbox2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Internal child Syntactik.MonoDevelop.License.ConfirmationStatusDialog.ActionArea
			global::Gtk.HButtonBox w9 = this.ActionArea;
			w9.Name = "dialog1_ActionArea";
			w9.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("_Cancel");
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w9[this.buttonCancel]));
			w10.Expand = false;
			w10.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 366;
			this.DefaultHeight = 157;
			this.buttonCancel.HasDefault = true;
			this.Hide();
		}
	}
}
